FROM node:20.12-alpine3.18

# Додано залежності
RUN apk update && apk add --no-cache git bash

WORKDIR /app/prof-service

RUN git clone -b db-postgres https://github.com/oshuster/prof-service.git .

RUN npm install

EXPOSE 8183

CMD ["npm", "start"]