FROM node:20.12-alpine3.18

# Додано залежності
RUN apk update && apk add --no-cache git bash python3 make g++

WORKDIR /app/filter-service

RUN git clone -b main https://github.com/oshuster/filter-service.git .

RUN npm install

EXPOSE 8182

CMD ["npm", "start"]